gautrigger_sync
amanalabs/gautrigger pull request #2
Opened 2022-05-25 11:51 UTC by alexey-vyrskiy

@sardeie pull request has been created.
Could you please check sources?
And I need about an hour for additional check and a little dev testing.

2022-05-26 06:21 UTC, sardeie requested changes
Thank you Alexey! Please see the requested changes in the comments.

2022-05-26 06:21 UTC, sardeie commented on force-app/main/default/objects/Allocation_To_OppPurpose_Field_Mapping__mdt/Allocation_To_OppPurpose_Field_Mapping__mdt.object-meta.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Did you create this to make the solution admin-configurable? If so, I would prefer to make this dev-controlled only, so please get rid of this custom metadata type and hard code the fields.

If there is another reason for it, please let me know.

2022-05-26 06:21 UTC, sardeie commented on force-app/main/default/objects/Opportunity_Purpose__c/fields/Unique_Allocation_Id__c.field-meta.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Client can create multiple Opportunity Purpose records for a single allocation. In our automation, we want to maintain a one-to-one mapping, but we don't want to enforce it so client has flexibility to make changes later.

2022-05-26 06:21 UTC, sardeie commented on force-app/main/default/flows/Unique_Allocation_Id_Filling.flow-meta.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Let's delete this. We don't want the enforce a unique one-to-one constraint.

2022-05-26 06:21 UTC, sardeie commented on force-app/main/default/classes/AllocationTriggerHandler.cls
> +    	AllocationToOppPurposeSyncHelper.collectRelatedOpportunityPurposesforDelete(oldMap);
Does this work? Are you sure static properties set in **before delete** will be available in **after delete**?

2022-05-26 07:34 UTC, alexey-vyrskiy commented on force-app/main/default/objects/Allocation_To_OppPurpose_Field_Mapping__mdt/Allocation_To_OppPurpose_Field_Mapping__mdt.object-meta.xml
> +<?xml version="1.0" encoding="UTF-8"?>
custom metadata mapping supposes only configuration without deploy.
Deleted
All fields hard coded  in Helper

2022-05-26 07:34 UTC, alexey-vyrskiy commented on force-app/main/default/objects/Opportunity_Purpose__c/fields/Unique_Allocation_Id__c.field-meta.xml
> +<?xml version="1.0" encoding="UTF-8"?>
fixed

2022-05-26 07:35 UTC, alexey-vyrskiy commented on force-app/main/default/flows/Unique_Allocation_Id_Filling.flow-meta.xml
> +<?xml version="1.0" encoding="UTF-8"?>
deleted

2022-05-26 07:36 UTC, alexey-vyrskiy commented on force-app/main/default/classes/AllocationTriggerHandler.cls
> +    	AllocationToOppPurposeSyncHelper.collectRelatedOpportunityPurposesforDelete(oldMap);
Yes, it definitely works and passed in test class.

2022-06-02 09:09 UTC, sardeie commented
Thank you @alexey-vyrskiy. Looks good. I'm merging it.

2022-06-02 09:09 UTC, merged